### ISSUE TITLE
Can't find c compiler on windows even when present

### ISSUE THREAD

**Issue by mbaklor** [fyne-io/setup#3]
A few times recently where people complain they have gcc installed and can find it in their path but the setup app doesn't find it.

Skimming through the code, it has to do with using `which` to find the compiler, which doesn't exist on windows that uses `where` instead.

**Comment by andydotxyz** [comment]
This is now fixed, thanks so much - a new build is up at https://geoffrey-artefacts.fynelabs.com/github/andydotxyz/fyne-io/setup/419/index.html
